version: '3.8'

services:
  ng360-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      ng360-network:
        driver: bridge
