# docker-compose.api.yml
services:
  ng360-api:
    image: ng360-api
    build: .
    container_name: ng360-api
    environment:
      - MONGODB_URI=mongodb://ng360-mongodb:27017/ng260
    ports:
      - "5000:5000"
    network_mode: "ng360-network"
