# docker-compose.api.yml
version: '3.8'

services:
  ng360-api:
    container_name: ng360-api
    # Replace with your API image
    image: ng360-api
    environment:
      - MONGODB_URI=mongodb://ng360-mongodb:27017/ng260
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    external: true
