name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Configure Git
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.NETGAZE_TOKEN }}@github.com" > ~/.git-credentials
      
      - name: Pull latest changes in deployment directory
        run: |
          cd /Users/admin/NetGaze360/api
          git fetch origin main
          git reset --hard origin/main
      
      - name: Set up Docker Compose
        run: |
          export PATH="$PATH:/Applications/Docker.app/Contents/Resources/bin"
          docker compose version
      
      - name: Build and deploy
        run: |
          export PATH="$PATH:/Applications/Docker.app/Contents/Resources/bin"
          cd /Users/admin/NetGaze360/api
          docker compose build ng360-api
          docker compose up -d --no-deps ng360-api

      - name: Clean up old images
        run: |
          export PATH="$PATH:/Applications/Docker.app/Contents/Resources/bin"
          docker image prune -f
